# Generated by Django 5.1.4 on 2026-01-24 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_url', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimDocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '001 Тип документа',
                'verbose_name_plural': '001 Типы документов',
                'db_table': '"app_doc"."dim_doc_type"',
            },
        ),
        migrations.CreateModel(
            name='DimDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('number', models.CharField(max_length=250, verbose_name='Название')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата вступления в силу')),
                ('date_stop', models.DateField(blank=True, null=True, verbose_name='Дата прекращения действия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_url.dimurl', verbose_name='Ссылка')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_doc.dimdoctype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': '002 Документ',
                'verbose_name_plural': '002 Документы',
                'db_table': '"app_doc"."dim_doc"',
                'ordering': ['date_start', 'date_stop', 'number'],
                'unique_together': {('doc_type', 'number', 'date_start')},
            },
        ),
    ]
