# Generated by Django 5.1.4 on 2026-01-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0002_dimdoc_author_dimdoc_updated_by_dimdoctype_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimdoc',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='dimdoctype',
            name='updated_by',
        ),
    ]
