# Generated by Django 5.1.4 on 2025-12-28 15:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalData',
            fields=[
                ('hash_address', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Хеш сумма')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('stand', models.CharField(blank=True, max_length=255, null=True, verbose_name='стенд')),
                ('table_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='тип таблицы')),
                ('group_catalog', models.CharField(blank=True, max_length=255, null=True, verbose_name='группа базы данных')),
                ('table_catalog', models.CharField(blank=True, max_length=255, null=True, verbose_name='имя базы данных')),
                ('table_schema', models.CharField(blank=True, max_length=255, null=True, verbose_name='схема таблицы')),
                ('table_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='имя таблицы')),
                ('table_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='комментарий таблицы')),
                ('column_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='номер столбца')),
                ('column_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='имя столбца')),
                ('column_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='комментарий столбца')),
                ('data_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='тип данных')),
                ('is_nullable', models.CharField(blank=True, max_length=255, null=True, verbose_name='поле пустое')),
                ('is_auto', models.CharField(blank=True, max_length=255, null=True, verbose_name='автоматическое')),
                ('column_info', models.JSONField(blank=True, null=True, verbose_name='дополнительная информация о данных')),
            ],
            options={
                'verbose_name': '00 Полная информация о данных.',
                'verbose_name_plural': '00 Полная информация о данных.',
                'db_table': 'app_dbm"."set_total_data',
            },
        ),
        migrations.CreateModel(
            name='DimColumnName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '08 Словарь имен столбцов.',
                'verbose_name_plural': '08 Словарь имен столбцов.',
                'db_table': 'app_dbm"."dim_column_name',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DimDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('version', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '02 Словарь баз данных.',
                'verbose_name_plural': '02 Словарь баз данных.',
                'db_table': 'app_dbm"."dim_db',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DimDBTableNameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '09 Словарь типов наименований.',
                'verbose_name_plural': '09 Словарь типов наименований.',
                'db_table': 'app_dbm"."dim_db_table_name_type',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DimDBTableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '05 Словарь тип таблицы.',
                'verbose_name_plural': '05 Словарь типы таблиц.',
                'db_table': 'app_dbm"."dim_table_type',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DimStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '01 Словарь слоев.',
                'verbose_name_plural': '01 Словарь слоев.',
                'db_table': 'app_dbm"."dim_stage',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DimTypeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '12 Справочник типов связей.',
                'verbose_name_plural': '12 Справочник типов связей.',
                'db_table': 'app_dbm"."dim_type_link',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='LinkDBSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('schema', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dbm.dimdb')),
            ],
            options={
                'verbose_name': '04 Схема.',
                'verbose_name_plural': '04 Схемы.',
                'db_table': 'app_dbm"."link_base_schemas',
                'unique_together': {('base', 'schema')},
            },
        ),
        migrations.CreateModel(
            name='LinkDBTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('is_metadata', models.BooleanField(default=True, verbose_name='метаданные')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dbm.linkdbschema')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dbm.dimdbtabletype')),
            ],
            options={
                'verbose_name': '10 Таблица.',
                'verbose_name_plural': '10 Таблицы',
                'db_table': 'app_dbm"."link_tables',
                'ordering': ['schema'],
                'unique_together': {('schema', 'type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LinkColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('date_create', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.CharField(max_length=255, null=True)),
                ('columns', models.CharField(max_length=255)),
                ('is_null', models.BooleanField(blank=True, db_default=True, null=True)),
                ('is_key', models.BooleanField(db_default=False)),
                ('unique_together', models.IntegerField(blank=True, null=True)),
                ('default', models.TextField(blank=True, null=True)),
                ('description', models.JSONField(blank=True, null=True)),
                ('stage', models.JSONField(blank=True, help_text='{"1": "Sand","2": "DEV", "3": "TEST","4": "PreProd", "5": "Prod",}', null=True, verbose_name='Доп. информация о слое')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dbm.linkdbtable')),
            ],
            options={
                'verbose_name': '11 Столбец.',
                'verbose_name_plural': '11 Столбцы.',
                'db_table': 'app_dbm"."link_columns',
                'ordering': ['columns'],
                'unique_together': {('table', 'columns')},
            },
        ),
        migrations.CreateModel(
            name='LinkColumnColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='app_dbm.linkcolumn')),
                ('sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='app_dbm.linkcolumn')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dbm.dimtypelink')),
            ],
            options={
                'verbose_name': '13 Связи столбцов.',
                'verbose_name_plural': '13 Связи столбцов.',
                'db_table': 'app_dbm"."link_columns_columns',
                'ordering': ['main'],
                'indexes': [models.Index(fields=['main'], name='link_column_main_id_519fdc_idx'), models.Index(fields=['sub'], name='link_column_sub_id_e817ba_idx'), models.Index(fields=['type'], name='link_column_type_id_964243_idx')],
                'constraints': [models.UniqueConstraint(fields=('main', 'sub', 'type'), name='unique_columns_relation'), models.UniqueConstraint(condition=models.Q(('sub__isnull', True)), fields=('main',), name='unique_main_only')],
                'unique_together': {('main', 'sub', 'type')},
            },
        ),
        migrations.CreateModel(
            name='LinkColumnName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dbm.linkcolumn')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dbm.dimcolumnname')),
            ],
            options={
                'verbose_name': '14 Связь столбцов и имен столбцов.',
                'verbose_name_plural': '14 Связь столбцов и имен столбцов.',
                'db_table': 'app_dbm"."link_columns_name',
                'ordering': ['name'],
                'unique_together': {('column', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LinkDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('version', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dbm.dimdb')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dbm.dimstage')),
            ],
            options={
                'verbose_name': '03 Базы данных.',
                'verbose_name_plural': '03 Базы данных.',
                'db_table': 'app_dbm"."link_db',
                'unique_together': {('name', 'host', 'port')},
            },
        ),
        migrations.CreateModel(
            name='LinkDBTableName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
                ('is_publish', models.BooleanField(blank=True, default=False, null=True, verbose_name='Указать как основное?')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dbm.linkdbtable')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dbm.dimdbtablenametype')),
            ],
            options={
                'verbose_name': '14 Альтернативное название таблицы.',
                'verbose_name_plural': '14 Альтернативные названия таблиц.',
                'db_table': 'app_dbm"."link_tables_name',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_publish', True)), fields=('table',), name='unique_publish_per_table')],
                'unique_together': {('table', 'name')},
            },
        ),
    ]
