# Generated by Django 5.1.4 on 2025-12-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dbm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimdb',
            options={'ordering': ['name'], 'verbose_name': '02 Словарь баз данных.', 'verbose_name_plural': '02 Словарь баз данных.'},
        ),
    ]
