# Generated by Django 5.1.4 on 2026-01-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dbm', '0002_dimcolumnname_author_dimcolumnname_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimcolumnname',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='dimdb',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='dimstage',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='dimtablenametype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='dimtabletype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='dimtypelink',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='linkcolumn',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='linkcolumncolumn',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='linkcolumnname',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='linkdb',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='linkschema',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='linktable',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='linktablename',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='totaldata',
            name='updated_by',
        ),
    ]
