# Generated by Django 5.1.4 on 2026-01-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dict', '0002_dimcategory_author_dimcategory_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimcategory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='dimdictionary',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='linkdictionaryname',
            name='updated_by',
        ),
    ]
