# Generated by Django 5.1.4 on 2025-07-15 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_dbm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimUpdateMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule', models.CharField(blank=True, max_length=50, null=True)),
                ('link_code', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '01 method update',
                'verbose_name_plural': '01 method update',
                'db_table': 'my_update"."dim_update_method',
            },
        ),
        migrations.CreateModel(
            name='LinkUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_dbm.linkcolumncolumn', verbose_name='Связь столбцов')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='my_updates.dimupdatemethod', verbose_name='Метод обновления')),
            ],
            options={
                'verbose_name': '02 Детали обновления',
                'verbose_name_plural': '02 Детали обновления',
                'db_table': 'my_update"."link_update',
                'unique_together': {('name', 'column')},
            },
        ),
    ]
