# Generated by Django 5.1.4 on 2026-01-31 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DimUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('url', models.URLField(max_length=2000, verbose_name='URL')),
                ('url_normalized', models.CharField(db_index=True, editable=False, max_length=2048, unique=True, verbose_name='Нормализованный URL (для уникальности)')),
                ('url_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Хэш URL')),
                ('login', models.CharField(blank=True, max_length=128, null=True, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP статус код')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен авторизации')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': '001 Ссылка',
                'verbose_name_plural': '001 Ссылки',
                'db_table': 'app_url"."dim_url',
                'ordering': ['url'],
            },
        ),
    ]
