# Generated by Django 5.1.4 on 2026-01-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_url', '0002_dimurl_author_dimurl_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimurl',
            name='updated_by',
        ),
    ]
