# Generated by Django 5.1.4 on 2025-07-15 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_dbm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255, verbose_name='Номер закона')),
            ],
            options={
                'verbose_name': '01 Закон.',
                'verbose_name_plural': '01 Законы.',
                'db_table': 'my_request"."link_fz',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='ColumnFZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_dbm.linkcolumn')),
                ('fz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_request.fz')),
            ],
            options={
                'verbose_name': '02 столбцы и законы.',
                'verbose_name_plural': '02 столбцы и законы.',
                'db_table': 'my_request"."link_column_fz',
                'unique_together': {('column', 'fz')},
            },
        ),
    ]
