# Generated by Django 4.1 on 2024-08-25 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnMDType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('md_type', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': '11 meta data Type',
                'verbose_name_plural': '11 meta data Type',
                'db_table': 'name_column_mdt',
                'ordering': ['md_type'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='base',
            name='hash_data',
        ),
        migrations.RemoveField(
            model_name='basegroup',
            name='hash_data',
        ),
        migrations.RemoveField(
            model_name='column',
            name='hash_data',
        ),
        migrations.RemoveField(
            model_name='columncolumn',
            name='hash_data',
        ),
        migrations.RemoveField(
            model_name='function',
            name='hash_data',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='hash_data',
        ),
        migrations.RemoveField(
            model_name='service',
            name='hash_data',
        ),
        migrations.RemoveField(
            model_name='servicetable',
            name='hash_data',
        ),
        migrations.RemoveField(
            model_name='stagecolumn',
            name='hash_data',
        ),
        migrations.RemoveField(
            model_name='stagefunction',
            name='hash_data',
        ),
        migrations.RemoveField(
            model_name='stagetype',
            name='hash_data',
        ),
        migrations.RemoveField(
            model_name='update',
            name='hash_data',
        ),
        migrations.RemoveField(
            model_name='updatemethod',
            name='hash_data',
        ),
        migrations.AddField(
            model_name='table',
            name='type',
            field=models.CharField(choices=[('tabl', 'Таблица'), ('ext_tabl', 'Внешняя таблица'), ('view', 'Представление')], default='tabl', max_length=10),
        ),
        migrations.AddField(
            model_name='update',
            name='link_code',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='host_db',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('schema', 'type', 'table_name')},
        ),
        migrations.RemoveField(
            model_name='table',
            name='hash_data',
        ),
        migrations.AddField(
            model_name='column',
            name='md_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dba.columnmdtype'),
        ),
    ]
