# Generated by Django 4.1 on 2024-09-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dba', '0002_columnmdtype_alter_table_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basegroup',
            name='hash_address',
            field=models.CharField(max_length=64, unique=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_com',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_name',
            field=models.CharField(max_length=150, verbose_name='название в БД'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_ru',
            field=models.TextField(verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='table',
            name='type',
            field=models.CharField(choices=[('tabl', 'Таблица'), ('ext_tabl', 'Внешняя таблица'), ('view', 'Представление')], default='tabl', max_length=10, verbose_name='Тип таблицы'),
        ),
    ]
