# Generated by Django 5.1.2 on 2024-10-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dba', '0003_alter_basegroup_hash_address_alter_table_table_com_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basegroup',
            name='hash_address',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='запись активна'),
        ),
    ]
