# Generated by Django 5.1.4 on 2025-07-15 15:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimColumnName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '08 Словарь имен столбцов.',
                'verbose_name_plural': '08 Словарь имен столбцов.',
                'db_table': 'my_dbmatch"."dim_column_name',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DimDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('version', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '03 Словарь баз данных.',
                'verbose_name_plural': '03 Словарь баз данных.',
                'db_table': 'my_dbmatch"."dim_db',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DimDBTableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '06 Словарь типов таблиц.',
                'verbose_name_plural': '06 Словарь типов таблиц.',
                'db_table': 'my_dbmatch"."dim_table_type',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DimStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '01 Словарь слоев.',
                'verbose_name_plural': '01 Словарь слоев.',
                'db_table': 'my_dbmatch"."dim_stage',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DimTypeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '12 Справочник типов связей.',
                'verbose_name_plural': '12 Справочник типов связей.',
                'db_table': 'my_dbmatch"."dim_type_link',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='LinkDBSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('schema', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_dbm.dimdb')),
            ],
            options={
                'verbose_name': '05 Словарь схем баз данных.',
                'verbose_name_plural': '05 Словарь схем баз данных.',
                'db_table': 'my_dbmatch"."link_base_schemas',
                'unique_together': {('base', 'schema')},
            },
        ),
        migrations.CreateModel(
            name='LinkDBTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('is_metadata', models.BooleanField(default=True, verbose_name='метаданные')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_dbm.linkdbschema')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_dbm.dimdbtabletype')),
            ],
            options={
                'verbose_name': '10 Связи схем и таблиц.',
                'verbose_name_plural': '10 Связи схем и таблиц',
                'db_table': 'my_dbmatch"."link_tables',
                'unique_together': {('schema', 'type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LinkColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('date_create', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.CharField(max_length=255, null=True)),
                ('columns', models.CharField(max_length=255)),
                ('is_null', models.BooleanField(blank=True, db_default=True, null=True)),
                ('is_key', models.BooleanField(db_default=False)),
                ('unique_together', models.IntegerField(blank=True, null=True)),
                ('default', models.TextField(blank=True, null=True)),
                ('description', models.JSONField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_dbm.linkdbtable')),
            ],
            options={
                'verbose_name': '11 Столбец.',
                'verbose_name_plural': '11 Столбцы.',
                'db_table': 'my_dbmatch"."link_columns',
                'unique_together': {('table', 'columns')},
            },
        ),
        migrations.CreateModel(
            name='LinkColumnColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main', to='my_dbm.linkcolumn')),
                ('sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub', to='my_dbm.linkcolumn')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_dbm.dimtypelink')),
            ],
            options={
                'verbose_name': '13 Связи столбцов.',
                'verbose_name_plural': '13 Связи столбцов.',
                'db_table': 'my_dbmatch"."link_columns_columns',
                'unique_together': {('main', 'sub', 'type')},
            },
        ),
        migrations.CreateModel(
            name='LinkColumnName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_dbm.linkcolumn')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_dbm.dimcolumnname')),
            ],
            options={
                'verbose_name': '14 Связь столбцов и имен столбцов.',
                'verbose_name_plural': '14 Связь столбцов и имен столбцов.',
                'db_table': 'my_dbmatch"."link_columns_name',
                'unique_together': {('column', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LinkColumnStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_dbm.linkcolumn')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_dbm.dimstage')),
            ],
            options={
                'verbose_name': '11 Связь столбца на стенде.',
                'verbose_name_plural': '11 Связь столбца на стенде.',
                'db_table': 'my_dbmatch"."link_columns_stage',
                'unique_together': {('stage', 'column')},
            },
        ),
        migrations.CreateModel(
            name='LinkDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('version', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('data_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_dbm.dimdb')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_dbm.dimstage')),
            ],
            options={
                'verbose_name': '04 Список баз данных.',
                'verbose_name_plural': '04 Список баз данных.',
                'db_table': 'my_dbmatch"."link_db',
                'unique_together': {('name', 'host', 'port')},
            },
        ),
        migrations.CreateModel(
            name='LinkDBTableName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_dbm.linkdbtable')),
            ],
            options={
                'verbose_name': '14 Альтернативное название таблицы.',
                'verbose_name_plural': '14 Альтернативные названия таблиц.',
                'db_table': 'my_dbmatch"."link_tables_name',
                'unique_together': {('table', 'name')},
            },
        ),
    ]
