# Generated by Django 5.1.4 on 2025-08-13 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dbm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('stage', models.CharField(max_length=255)),
                ('db_version', models.CharField(max_length=255)),
                ('db_name', models.CharField(max_length=255)),
                ('db_description', models.TextField(blank=True, null=True)),
                ('schem_name', models.CharField(max_length=255)),
                ('schem_description', models.TextField(blank=True, null=True)),
                ('tab_is_metadata', models.BooleanField(default=True, verbose_name='метаданные')),
                ('tab_type', models.CharField(max_length=255)),
                ('tab_name', models.CharField(max_length=255)),
                ('tab_description', models.TextField(blank=True, null=True)),
                ('col_date_create', models.DateTimeField(default=datetime.datetime.now)),
                ('col_type', models.CharField(max_length=255, null=True)),
                ('col_columns', models.CharField(max_length=255)),
                ('col_is_null', models.BooleanField(blank=True, db_default=True, null=True)),
                ('col_is_key', models.BooleanField(db_default=False)),
                ('col_unique_together', models.IntegerField(blank=True, null=True)),
                ('col_default', models.TextField(blank=True, null=True)),
                ('col_description', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '00 Полная информация о данных.',
                'verbose_name_plural': '00 Полная информация о данных.',
                'db_table': 'my_dbmatch"."link_total_data',
            },
        ),
    ]
