# Generated by Django 5.1.2 on 2025-08-10 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_dbm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SyncDatabase',
        ),
    ]
