# Generated by Django 5.1.4 on 2025-08-21 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dbm', '0002_totaldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkdb',
            name='data_base',
        ),
        migrations.RemoveField(
            model_name='linkdbtablename',
            name='description',
        ),
        migrations.AddField(
            model_name='linkdb',
            name='base',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_dbm.dimdb'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkcolumn',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_dbm.linkdbtable'),
        ),
        migrations.AlterField(
            model_name='linkcolumncolumn',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='my_dbm.linkcolumn'),
        ),
        migrations.AlterField(
            model_name='linkcolumncolumn',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='my_dbm.linkcolumn'),
        ),
        migrations.AlterField(
            model_name='linkcolumncolumn',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_dbm.dimtypelink'),
        ),
        migrations.AlterField(
            model_name='linkcolumnname',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_dbm.linkcolumn'),
        ),
        migrations.AlterField(
            model_name='linkcolumnname',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_dbm.dimcolumnname'),
        ),
        migrations.AlterField(
            model_name='linkcolumnstage',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_dbm.linkcolumn'),
        ),
        migrations.AlterField(
            model_name='linkcolumnstage',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_dbm.dimstage'),
        ),
        migrations.AlterField(
            model_name='linkdb',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_dbm.dimstage'),
        ),
        migrations.AlterField(
            model_name='linkdbschema',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_dbm.dimdb'),
        ),
        migrations.AlterField(
            model_name='linkdbtable',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_dbm.linkdbschema'),
        ),
        migrations.AlterField(
            model_name='linkdbtable',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_dbm.dimdbtabletype'),
        ),
        migrations.AlterField(
            model_name='linkdbtablename',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_dbm.linkdbtable'),
        ),
        migrations.CreateModel(
            name='DimDBTableNameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '08 Словарь типов наименований.',
                'verbose_name_plural': '08 Словарь типов наименований.',
                'db_table': 'my_dbmatch"."dim_db_table_name_type',
                'unique_together': {('name',)},
            },
        ),
        migrations.AddField(
            model_name='linkdbtablename',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_dbm.dimdbtablenametype'),
        ),
    ]
