# Generated by Django 5.1.2 on 2025-08-20 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dbm', '0002_delete_syncdatabase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkdbtablename',
            name='description',
        ),
        migrations.CreateModel(
            name='DimDBTableNameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '08 Словарь типов наименований.',
                'verbose_name_plural': '08 Словарь типов наименований.',
                'db_table': 'my_dbmatch"."dim_db_table_name_type',
                'unique_together': {('name',)},
            },
        ),
        migrations.AddField(
            model_name='linkdbtablename',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_dbm.dimdbtablenametype'),
            preserve_default=False,
        ),
    ]
