# Generated by Django 5.1.4 on 2025-09-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dbm', '0003_remove_linkdb_data_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkcolumn',
            name='stage',
            field=models.JSONField(blank=True, help_text='{"1": "Sand","2": "DEV", "3": "TEST","4": "PreProd", "5": "Prod",}', null=True, verbose_name='Доп. информация о слое'),
        ),
    ]
