# Generated by Django 5.1.4 on 2025-09-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_dbm', '0004_linkcolumn_stage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkColumnStage',
        ),
    ]
