# Generated by Django 5.1.4 on 2025-09-12 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dbm', '0005_delete_linkcolumnstage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimdb',
            options={'verbose_name': '02 Словарь баз данных.', 'verbose_name_plural': '02 Словарь баз данных.'},
        ),
        migrations.AlterModelOptions(
            name='dimdbtabletype',
            options={'verbose_name': '05 Словарь тип таблицы.', 'verbose_name_plural': '05 Словарь типы таблиц.'},
        ),
        migrations.AlterModelOptions(
            name='linkdb',
            options={'verbose_name': '03 Список баз данных.', 'verbose_name_plural': '03 Список баз данных.'},
        ),
        migrations.AlterModelOptions(
            name='linkdbschema',
            options={'verbose_name': '04 Схема базы данных.', 'verbose_name_plural': '04 Схемы баз данных.'},
        ),
        migrations.AlterModelOptions(
            name='linkdbtable',
            options={'verbose_name': '10 Таблица.', 'verbose_name_plural': '10 Таблицы'},
        ),
        migrations.AddField(
            model_name='linkdbtablename',
            name='is_publish',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='linkdbtablename',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_dbm.dimdbtablenametype'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='linkdbtablename',
            constraint=models.UniqueConstraint(condition=models.Q(('is_publish', True)), fields=('table',), name='unique_publish_per_table'),
        ),
    ]
