# Generated by Django 5.1.4 on 2025-09-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dbm', '0006_alter_dimdb_options_alter_dimdbtabletype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkdbtablename',
            name='is_publish',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Указать как основное?'),
        ),
        migrations.AddIndex(
            model_name='linkcolumncolumn',
            index=models.Index(fields=['main'], name='link_column_main_id_519fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='linkcolumncolumn',
            index=models.Index(fields=['sub'], name='link_column_sub_id_e817ba_idx'),
        ),
        migrations.AddIndex(
            model_name='linkcolumncolumn',
            index=models.Index(fields=['type'], name='link_column_type_id_964243_idx'),
        ),
        migrations.AddConstraint(
            model_name='linkcolumncolumn',
            constraint=models.UniqueConstraint(fields=('main', 'sub', 'type'), name='unique_columns_relation'),
        ),
        migrations.AddConstraint(
            model_name='linkcolumncolumn',
            constraint=models.UniqueConstraint(condition=models.Q(('sub__isnull', True)), fields=('main',), name='unique_main_only'),
        ),
    ]
