# Generated by Django 5.0 on 2023-12-31 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Админ поле. Создано', verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Админ поле. Обновлено', verbose_name='дата изменения')),
                ('hash_address', models.CharField(db_comment='адрес данных по хеш', max_length=64, unique=True)),
                ('hash_data', models.CharField(db_comment='хеш сумма части строки', max_length=64, unique=True)),
                ('is_active', models.BooleanField(db_comment='Админ поле. Актуально', default=True, verbose_name='запись активна')),
                ('service', models.CharField(db_comment='Имя базы группы', max_length=150)),
            ],
            options={
                'verbose_name': '08 service',
                'verbose_name_plural': '08 service',
                'db_table': 'name_service',
                'db_table_comment': 'Список сервисов.',
                'ordering': ['service'],
            },
        ),
        migrations.AlterModelOptions(
            name='stagetype',
            options={'ordering': ['pk'], 'verbose_name': '07 Stage', 'verbose_name_plural': '07 Stage'},
        ),
        migrations.CreateModel(
            name='ServiceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Админ поле. Создано', verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Админ поле. Обновлено', verbose_name='дата изменения')),
                ('hash_address', models.CharField(db_comment='адрес данных по хеш', max_length=64, unique=True)),
                ('hash_data', models.CharField(db_comment='хеш сумма части строки', max_length=64, unique=True)),
                ('is_active', models.BooleanField(db_comment='Админ поле. Актуально', default=True, verbose_name='запись активна')),
                ('service', models.ForeignKey(blank=True, db_comment='Сервис', null=True, on_delete=django.db.models.deletion.PROTECT, to='dba.service')),
                ('table', models.ForeignKey(blank=True, db_comment='Таблица', null=True, on_delete=django.db.models.deletion.PROTECT, to='dba.table')),
            ],
            options={
                'verbose_name': '09 Service Table',
                'verbose_name_plural': '09 Service Table',
                'db_table': 'name_service_table',
                'db_table_comment': 'Группы таблиц - сервисы.',
                'ordering': ['service', 'table'],
                'unique_together': {('service', 'table')},
            },
        ),
    ]
