# Generated by Django 5.0 on 2024-01-04 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dba', '0002_service_alter_stagetype_options_servicetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Админ поле. Создано', verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Админ поле. Обновлено', verbose_name='дата изменения')),
                ('hash_address', models.CharField(db_comment='адрес данных по хеш', max_length=64, unique=True)),
                ('hash_data', models.CharField(db_comment='хеш сумма части строки', max_length=64, unique=True)),
                ('is_active', models.BooleanField(db_comment='Админ поле. Актуально', default=True, verbose_name='запись активна')),
                ('method', models.CharField(blank=True, db_comment='Тип обновления', max_length=255, null=True)),
            ],
            options={
                'verbose_name': '04 method update',
                'verbose_name_plural': '04 method update',
                'db_table': 'link_update_method',
                'db_table_comment': 'Способ обновления.',
            },
        ),
        migrations.AlterModelOptions(
            name='base',
            options={'ordering': ['base', 'type'], 'verbose_name': '01 Base', 'verbose_name_plural': '01 Base'},
        ),
        migrations.AlterModelOptions(
            name='basegroup',
            options={'ordering': ['table_catalog'], 'verbose_name': '02 BaseGroup', 'verbose_name_plural': '02 BaseGroup'},
        ),
        migrations.AlterModelOptions(
            name='schema',
            options={'ordering': ['base', 'table_schema'], 'verbose_name': '03 Schema', 'verbose_name_plural': '03 Schema'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['schema', 'table_name'], 'verbose_name': '04 Table', 'verbose_name_plural': '04 Table'},
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'verbose_name': '04 update', 'verbose_name_plural': '04 update'},
        ),
        migrations.AddField(
            model_name='update',
            name='method',
            field=models.ForeignKey(blank=True, db_comment='Метод', null=True, on_delete=django.db.models.deletion.PROTECT, to='dba.updatemethod'),
        ),
    ]
