# Generated by Django 5.1.2 on 2025-08-20 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='phone',
        ),
    ]
