# Generated by Django 5.1.4 on 2025-07-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0002_userloginstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='link_profile',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на профиль'),
        ),
    ]
