# Generated by Django 5.1.4 on 2025-08-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0003_myprofile_link_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='phone',
        ),
    ]
