# Generated by Django 5.1.4 on 2025-08-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCheckSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_expression', models.CharField(default='0 0 0 1 * * *', help_text='Формат: сек мин час день месяц день_неделя год (например, "0 1 * * * * *")', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '10 Расписание проверки ссылок (cron)',
                'verbose_name_plural': '10 Расписание проверки ссылок (cron)',
                'db_table': 'my_services"."dim_schedule',
            },
        ),
        migrations.AlterModelOptions(
            name='dimlink',
            options={'verbose_name': '09 ссылки.', 'verbose_name_plural': '09 ссылки.'},
        ),
        migrations.AlterModelOptions(
            name='dimservices',
            options={'verbose_name': '07 Список сервисов.', 'verbose_name_plural': '07 Список сервисов.'},
        ),
        migrations.AlterModelOptions(
            name='linkservicesservices',
            options={'verbose_name': '08 Группировки сервисов.', 'verbose_name_plural': '08 Группировки сервисов.'},
        ),
        migrations.AlterModelOptions(
            name='linkservicestable',
            options={'verbose_name': '09 Таблицы сервиса.', 'verbose_name_plural': '09 Таблицы сервиса.'},
        ),
        migrations.AddField(
            model_name='dimlink',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последней проверки'),
        ),
        migrations.AddField(
            model_name='dimlink',
            name='status_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='HTTP статус код'),
        ),
    ]
