# Generated by Django 5.1.4 on 2026-01-03 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_dbm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnGroupName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255, verbose_name='Номер закона')),
            ],
            options={
                'verbose_name': '03 название групп столбцов.',
                'verbose_name_plural': '03 названия групп столбцов.',
                'db_table': 'app_request"."dim_columns_group',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='TableGroupName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255, verbose_name='Имя таблицы')),
            ],
            options={
                'verbose_name': '01 название групп таблиц.',
                'verbose_name_plural': '01 названия групп таблиц.',
                'db_table': 'app_request"."dim_table_group',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='ColumnGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_dbm.linkcolumn')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_request.columngroupname')),
            ],
            options={
                'verbose_name': '04 группа столбцов.',
                'verbose_name_plural': '03 группы столбцов.',
                'db_table': 'app_request"."link_column_group',
                'unique_together': {('column', 'group_name')},
            },
        ),
        migrations.CreateModel(
            name='TableGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_dbm.linkcolumn')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_request.tablegroupname')),
            ],
            options={
                'verbose_name': '02 группа таблиц.',
                'verbose_name_plural': '02 группы таблиц.',
                'db_table': 'app_request"."link_table_group',
                'unique_together': {('table', 'group_name')},
            },
        ),
    ]
