# Generated by Django 5.1.4 on 2026-01-24 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_dbm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnGroupName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255, verbose_name='Номер закона')),
            ],
            options={
                'verbose_name': '03 Название групп столбцов',
                'verbose_name_plural': '03 Названия групп столбцов',
                'db_table': '"app_request"."dim_columns_group"',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='TableGroupName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255, verbose_name='Имя таблицы')),
            ],
            options={
                'verbose_name': '01 Название групп таблиц',
                'verbose_name_plural': '01 Названия групп таблиц',
                'db_table': '"app_request"."dim_table_group"',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='ColumnGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_dbm.linkcolumn', verbose_name='Столбец')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_request.columngroupname', verbose_name='Группа столбцов')),
            ],
            options={
                'verbose_name': '04 Группа столбцов',
                'verbose_name_plural': '04 Группы столбцов',
                'db_table': '"app_request"."link_column_group"',
                'unique_together': {('column', 'group_name')},
            },
        ),
        migrations.CreateModel(
            name='TableGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_dbm.linktable', verbose_name='Таблица')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_request.tablegroupname', verbose_name='Группа')),
            ],
            options={
                'verbose_name': '02 Группа таблиц',
                'verbose_name_plural': '02 Группы таблиц',
                'db_table': '"app_request"."link_table_group"',
                'unique_together': {('table', 'group_name')},
            },
        ),
    ]
