# Generated by Django 5.1.4 on 2026-01-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_request', '0002_columngroup_author_columngroup_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columngroup',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='columngroupname',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='tablegroup',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='tablegroupname',
            name='updated_by',
        ),
    ]
