# Generated by Django 5.1.4 on 2025-12-24 20:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, help_text='Флаг подтверждения аккаунта администратором', verbose_name='Одобрен')),
                ('link_profile', models.URLField(blank=True, help_text='Ссылка на внешний профиль (соц. сети, портфолио и т.д.)', null=True, verbose_name='Профиль')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания профиля', verbose_name='Дата создания')),
                ('user', models.OneToOneField(help_text='Связанный пользователь Django', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'db_table': 'app_auth"."profile',
            },
        ),
        migrations.CreateModel(
            name='UserLoginStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateField(help_text='Дата, за которую собирается статистика входов', verbose_name='Дата входа')),
                ('login_count', models.PositiveSmallIntegerField(default=1, help_text='Количество входов пользователя за указанную дату', verbose_name='Количество входов')),
                ('first_login_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Время первого входа пользователя в указанную дату', verbose_name='Первый вход')),
                ('last_login_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Время последнего входа пользователя в указанную дату', verbose_name='Последний вход')),
                ('user', models.ForeignKey(help_text='Пользователь, для которого собирается статистика', on_delete=django.db.models.deletion.CASCADE, related_name='login_stats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика входа',
                'verbose_name_plural': 'Статистика входов',
                'db_table': 'app_auth"."user_login_stats',
                'ordering': ['-login_date', 'user'],
                'indexes': [models.Index(fields=['user', 'login_date'], name='user_login__user_id_efb5da_idx'), models.Index(fields=['login_date'], name='user_login__login_d_1b5716_idx')],
                'unique_together': {('user', 'login_date')},
            },
        ),
    ]
