# Generated by Django 5.2.7 on 2026-01-22 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
        ('app_url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_url.dimurl', verbose_name='Ссылка на профиль'),
        ),
    ]
