# Generated by Django 5.1.4 on 2025-12-28 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateField(verbose_name='Дата входа')),
                ('login_count', models.PositiveIntegerField(default=1, verbose_name='Количество входов за день')),
                ('first_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Первый вход в этот день')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход в этот день')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_stats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика входов',
                'verbose_name_plural': 'Статистики входов',
                'db_table': 'app_auth"."login_stat',
                'unique_together': {('user', 'login_date')},
            },
        ),
    ]
