# Generated by Django 5.1.4 on 2026-02-06 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('url', models.CharField(max_length=500, verbose_name='URL страницы')),
                ('path', models.CharField(db_index=True, max_length=500, verbose_name='Путь')),
                ('view_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название представления')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP метод')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('referrer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Источник перехода')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ключ сессии')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='Время ответа (сек)')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP статус')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог посещения',
                'verbose_name_plural': 'Логи посещений',
                'db_table': 'app_auth"."user_visit_log',
            },
        ),
    ]
