# Generated by Django 5.1.4 on 2025-12-28 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_loginstat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myprofile',
            options={},
        ),
    ]
