# Generated by Django 5.2.7 on 2026-01-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_myprofile_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='link_profile',
        ),
    ]
