# Generated by Django 5.1.4 on 2026-01-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_registrationrequest_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='updated_by',
        ),
    ]
