# Generated by Django 5.1.2 on 2025-08-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimservices',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='код сервиса.'),
        ),
    ]
