# Generated by Django 5.1.4 on 2025-08-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_services', '0002_linkcheckschedule_alter_dimlink_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimservices',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='код сервиса.'),
        ),
    ]
