# Generated by Django 5.1.4 on 2025-08-21 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_services', '0003_dimservices_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimServicesNameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '08 Словарь типов наименований.',
                'verbose_name_plural': '08 Словарь типов наименований.',
                'db_table': 'my_services"."dim_service_name_type',
                'unique_together': {('name',)},
            },
        ),
        migrations.AddField(
            model_name='dimservicesname',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_services.dimservicesnametype'),
        ),
    ]
