# Generated by Django 5.1.2 on 2025-08-20 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_services', '0003_dimservicesnametype_dimservicesname_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimservicesname',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_services.dimservicesnametype'),
        ),
    ]
