# Generated by Django 5.1.4 on 2026-01-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_query_path', '0002_answeroption_author_answeroption_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeroption',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_by',
        ),
    ]
