# Generated by Django 5.1.2 on 2025-05-19 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('hash_address', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': '0100 Имена баз данных',
                'verbose_name_plural': '0100 Имена баз данных',
                'db_table': 'my_metla"."dim_base_name',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('hash_address', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255, verbose_name='Тип баз данных')),
            ],
            options={
                'verbose_name': '0100 Тип базы данных',
                'verbose_name_plural': '0100 Типы баз данных',
                'db_table': 'my_metla"."dim_base_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ColumnName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('hash_address', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название столбца')),
            ],
            options={
                'verbose_name': '0401 Имена столбца',
                'verbose_name_plural': '0401 Имена столбцов',
                'db_table': 'my_metla"."dim_column_name',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ColumnType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('hash_address', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255, verbose_name='Тип столбца')),
            ],
            options={
                'verbose_name': '0400 Тип столбца',
                'verbose_name_plural': '0400 Типы столбцов',
                'db_table': 'my_metla"."dim_column_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('hash_address', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
            ],
            options={
                'verbose_name': '0010 Среда разработки',
                'verbose_name_plural': '0010 Среды разработки',
                'db_table': 'my_metla"."dim_environment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchemaName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('hash_address', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '0201 Схема',
                'verbose_name_plural': '0201 Схемы',
                'db_table': 'my_metla"."dim_schema',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('hash_address', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255, verbose_name='Название в БД')),
            ],
            options={
                'verbose_name': '0301 Список таблиц',
                'verbose_name_plural': '0301 Список таблиц',
                'db_table': 'my_metla"."dim_tables',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('hash_address', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255, verbose_name='Тип таблицы')),
            ],
            options={
                'verbose_name': '0300 Тип таблицы',
                'verbose_name_plural': '0300 Типы таблиц',
                'db_table': 'my_metla"."dim_table_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('hash_address', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('host_name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_metla.basename')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_metla.basetype')),
                ('env', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_metla.environment')),
            ],
            options={
                'verbose_name': '0101 База',
                'verbose_name_plural': '0101 Базы',
                'db_table': 'my_metla"."dim_bases',
                'ordering': ['env', 'name', 'type'],
                'unique_together': {('env', 'name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('hash_address', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('is_nullable', models.BooleanField(blank=True, null=True, verbose_name='Возможен ли ноль')),
                ('is_auto', models.BooleanField(blank=True, null=True, verbose_name='Автоматическое заполнение')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_metla.columnname', verbose_name='Название столбца')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_metla.columntype', verbose_name='Тип данных')),
            ],
            options={
                'verbose_name': '0401 Столбец',
                'verbose_name_plural': '0401 Столбцы',
                'db_table': 'my_metla"."dim_columns',
                'ordering': ['type', 'name'],
                'unique_together': {('type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BaseSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('hash_address', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('description', models.TextField(blank=True, null=True)),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_metla.base')),
                ('env', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_metla.environment')),
                ('schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='my_metla.schemaname')),
            ],
            options={
                'verbose_name': '1000 База-схема-таблица',
                'verbose_name_plural': '1000 База-схема-таблицы',
                'db_table': 'my_metla"."link_base_schema',
                'ordering': ['base'],
                'unique_together': {('base', 'schema')},
            },
        ),
        migrations.CreateModel(
            name='SchemaTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('hash_address', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('table_is_metadata', models.BooleanField(default=False, verbose_name='Таблица метаданных')),
                ('description', models.TextField(blank=True, null=True)),
                ('base_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_metla.baseschema')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_metla.table')),
                ('table_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_metla.tabletype')),
            ],
            options={
                'verbose_name': '2000 схема-таблица.',
                'verbose_name_plural': '2000 схемы-таблиц',
                'db_table': 'my_metla"."link_schema_table',
                'ordering': ['table'],
                'unique_together': {('base_schema', 'table')},
            },
        ),
        migrations.CreateModel(
            name='TableColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('hash_address', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('numbers', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_metla.column')),
                ('schema_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_metla.schematable')),
            ],
            options={
                'verbose_name': '3000 таблица-столбец.',
                'verbose_name_plural': '3000 таблицы-столбецы',
                'db_table': 'my_metla"."link_table_column',
                'ordering': ['numbers'],
                'unique_together': {('schema_table', 'column')},
            },
        ),
    ]
