# Generated by Django 5.1.2 on 2025-05-20 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_metla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecolumn',
            name='is_auto',
            field=models.BooleanField(blank=True, null=True, verbose_name='Автоматическое заполнение'),
        ),
        migrations.AddField(
            model_name='tablecolumn',
            name='is_nullable',
            field=models.BooleanField(blank=True, null=True, verbose_name='Возможен ли ноль'),
        ),
        migrations.AddField(
            model_name='tablecolumn',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_metla.columnname', verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='tablecolumn',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_metla.columntype', verbose_name='Тип данных'),
        ),
    ]
