# Generated by Django 5.1.2 on 2025-05-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_metla', '0002_tablecolumn_is_auto_tablecolumn_is_nullable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='is_auto',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Автоматическое заполнение'),
        ),
        migrations.AlterField(
            model_name='column',
            name='is_nullable',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Возможен ли ноль'),
        ),
    ]
