# Generated by Django 5.1.2 on 2025-05-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_metla', '0003_alter_column_is_auto_alter_column_is_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecolumn',
            name='is_auto',
            field=models.BooleanField(blank=True, default=False, verbose_name='Автоматическое заполнение'),
        ),
        migrations.AlterField(
            model_name='tablecolumn',
            name='is_nullable',
            field=models.BooleanField(blank=True, default=True, verbose_name='Возможен ли ноль'),
        ),
    ]
