# Generated by Django 5.1.4 on 2026-01-03 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_dbm', '0001_initial'),
        ('app_doc', '0001_initial'),
        ('app_url', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DimRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '001 Роли в сервисе.',
                'verbose_name_plural': '001 Роли в сервисах.',
                'db_table': 'app_services"."dim_roles',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DimServicesNameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '08 Словарь типов наименований.',
                'verbose_name_plural': '08 Словарь типов наименований.',
                'db_table': 'app_services"."dim_services_name_type',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DimServicesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '02 Типы сервисов.',
                'verbose_name_plural': '02 Типы сервисов.',
                'db_table': 'app_services"."dim_services_type',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DimServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('alias', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_services.dimservicestypes')),
            ],
            options={
                'verbose_name': '07 Список сервисов.',
                'verbose_name_plural': '07 Список сервисов.',
                'db_table': 'app_services"."dim_services',
                'ordering': ['alias'],
                'unique_together': {('alias', 'type')},
            },
        ),
        migrations.CreateModel(
            name='DimTechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '06 Технология.',
                'verbose_name_plural': '06 Технологии.',
                'db_table': 'app_services"."link_tech_stack',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DimServicesName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_services.dimservices')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_services.dimservicesnametype')),
            ],
            options={
                'verbose_name': '03 Синонимы сервисов.',
                'verbose_name_plural': '03 Синонимы сервисов.',
                'db_table': 'app_services"."dim_services_name',
                'unique_together': {('alias', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LinkDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_doc.dimdoc')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_services.dimservices')),
            ],
            options={
                'verbose_name': '011 Сервис и документ',
                'verbose_name_plural': '011 Сервисы и документы',
                'db_table': 'app_services"."link_doc',
                'unique_together': {('services', 'doc')},
            },
        ),
        migrations.CreateModel(
            name='LinkResponsiblePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_services.dimroles')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_services.dimservices')),
            ],
            options={
                'verbose_name': '04 Ответственные за сервис.',
                'verbose_name_plural': '04 Ответственные за сервис.',
                'db_table': 'app_services"."link_responsible_person',
                'unique_together': {('service', 'role', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LinkServicesServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_main', to='app_services.dimservices')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_sub', to='app_services.dimservices')),
            ],
            options={
                'verbose_name': '08 Группировки сервисов.',
                'verbose_name_plural': '08 Группировки сервисов.',
                'db_table': 'app_services"."link_services_services',
                'unique_together': {('main', 'sub')},
            },
        ),
        migrations.CreateModel(
            name='LinkServicesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_services.dimservices')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_dbm.linktable')),
            ],
            options={
                'verbose_name': '09 Таблицы сервиса.',
                'verbose_name_plural': '09 Таблицы сервиса.',
                'db_table': 'app_services"."link_service_table',
                'unique_together': {('service', 'table')},
            },
        ),
        migrations.CreateModel(
            name='LinksUrlService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('link_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_services.dimservices')),
                ('stack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_services.dimtechstack')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_dbm.dimstage')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_url.dimurl')),
            ],
            options={
                'verbose_name': '09 ссылки.',
                'verbose_name_plural': '09 ссылки.',
                'db_table': 'app_services"."Link_url_service',
                'ordering': ['url'],
                'unique_together': {('url',)},
            },
        ),
    ]
