# Generated by Django 5.1.4 on 2025-12-29 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_dbm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DimSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkCheckSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_expression', models.CharField(default='0 0 0 1 * * *', help_text='Формат: сек мин час день месяц день_неделя год (например, "0 1 * * * * *")', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '10 Расписание проверки ссылок (cron)',
                'verbose_name_plural': '10 Расписание проверки ссылок (cron)',
                'db_table': 'app_services"."dim_schedule',
            },
        ),
        migrations.CreateModel(
            name='DimRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '01 Роли в сервисе.',
                'verbose_name_plural': '01 Роли в сервисах.',
                'db_table': 'app_services"."dim_roles',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DimServicesNameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '08 Словарь типов наименований.',
                'verbose_name_plural': '08 Словарь типов наименований.',
                'db_table': 'app_services"."dim_services_name_type',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DimServicesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '02 Типы сервисов.',
                'verbose_name_plural': '02 Типы сервисов.',
                'db_table': 'app_services"."dim_services_type',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DimServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='код сервиса.')),
                ('alias', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_services.dimservicestypes')),
            ],
            options={
                'verbose_name': '07 Список сервисов.',
                'verbose_name_plural': '07 Список сервисов.',
                'db_table': 'app_services"."dim_services',
                'ordering': ['alias'],
                'unique_together': {('alias', 'type')},
            },
        ),
        migrations.CreateModel(
            name='DimTechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '06 Технология.',
                'verbose_name_plural': '06 Технологии.',
                'db_table': 'app_services"."link_tech_stack',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DimServicesName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_services.dimservices')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_services.dimservicesnametype')),
            ],
            options={
                'verbose_name': '03 Синонимы сервисов.',
                'verbose_name_plural': '03 Синонимы сервисов.',
                'db_table': 'app_services"."dim_services_name',
                'unique_together': {('alias', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DimLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('link', models.URLField(blank=True, null=True)),
                ('link_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='Время последней проверки')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP статус код')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_dbm.dimstage')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_services.dimservices')),
                ('stack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_services.dimtechstack')),
            ],
            options={
                'verbose_name': '09 ссылки.',
                'verbose_name_plural': '09 ссылки.',
                'db_table': 'app_services"."dim_link',
                'ordering': ['link'],
                'unique_together': {('link',)},
            },
        ),
        migrations.CreateModel(
            name='LinkResponsiblePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_services.dimroles')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_services.dimservices')),
            ],
            options={
                'verbose_name': '04 Ответственные за сервис.',
                'verbose_name_plural': '04 Ответственные за сервис.',
                'db_table': 'app_services"."link_responsible_person',
                'unique_together': {('service', 'role', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LinkServicesServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_main', to='app_services.dimservices')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_sub', to='app_services.dimservices')),
            ],
            options={
                'verbose_name': '08 Группировки сервисов.',
                'verbose_name_plural': '08 Группировки сервисов.',
                'db_table': 'app_services"."link_services_services',
                'unique_together': {('main', 'sub')},
            },
        ),
        migrations.CreateModel(
            name='LinkServicesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_services.dimservices')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_dbm.linkdbtable')),
            ],
            options={
                'verbose_name': '09 Таблицы сервиса.',
                'verbose_name_plural': '09 Таблицы сервиса.',
                'db_table': 'app_services"."link_service_table',
                'unique_together': {('service', 'table')},
            },
        ),
    ]
