# Generated by Django 5.1.4 on 2026-01-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0002_dimroles_author_dimroles_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimroles',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='dimservices',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='dimservicesname',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='dimservicesnametype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='dimservicestypes',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='dimtechstack',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='linkdoc',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='linkresponsibleperson',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='linkservicesservices',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='linkservicestable',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='linksurlservice',
            name='updated_by',
        ),
    ]
