# Generated by Django 5.1.4 on 2026-01-04 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_dbm', '0001_initial'),
        ('app_url', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimUpdateMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('schedule', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_url.dimurl')),
            ],
            options={
                'verbose_name': '01 метод обновления',
                'verbose_name_plural': '01 методы обновлений',
                'db_table': 'app_updates"."dim_update_method',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LinkUpdateCol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_main', to='app_dbm.linkcolumn')),
                ('sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_sub', to='app_dbm.linkcolumn')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_updates.dimupdatemethod')),
            ],
            options={
                'verbose_name': '02 обновление столбцов.',
                'verbose_name_plural': '02 обновление столбцов.',
                'db_table': 'app_updates"."link_update_col',
                'ordering': ['main'],
                'indexes': [models.Index(fields=['main'], name='link_update_main_id_5bf758_idx'), models.Index(fields=['sub'], name='link_update_sub_id_ed569d_idx'), models.Index(fields=['type'], name='link_update_type_id_377096_idx')],
                'constraints': [models.UniqueConstraint(fields=('main', 'sub', 'type'), name='unique_update_columns_relation'), models.UniqueConstraint(condition=models.Q(('sub__isnull', True)), fields=('main',), name='unique_update_main_only')],
                'unique_together': {('main', 'sub', 'type')},
            },
        ),
    ]
