# Generated by Django 5.1.4 on 2026-01-31 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_dbm', '0001_initial'),
        ('app_url', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DimUpdateMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название метода')),
                ('schedule', models.CharField(blank=True, max_length=50, null=True, verbose_name='Расписание')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание расписания.')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_url.dimurl', verbose_name='Ссылка на источник')),
            ],
            options={
                'verbose_name': '01 Метод обновления',
                'verbose_name_plural': '01 Методы обновлений',
                'db_table': 'app_updates"."dim_update_method',
                'ordering': ['name', 'schedule'],
            },
        ),
        migrations.CreateModel(
            name='LinkUpdateCol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_main', to='app_dbm.linkcolumn', verbose_name='Основная колонка')),
                ('sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_sub', to='app_dbm.linkcolumn', verbose_name='Дополнительная колонка')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_updates.dimupdatemethod', verbose_name='Метод обновления')),
            ],
            options={
                'verbose_name': '02 Обновление столбцов',
                'verbose_name_plural': '02 Обновления столбцов',
                'db_table': 'app_updates"."link_update_col',
                'ordering': ['main'],
            },
        ),
        migrations.AddIndex(
            model_name='dimupdatemethod',
            index=models.Index(fields=['name'], name='dim_update__name_b8501a_idx'),
        ),
        migrations.AddIndex(
            model_name='dimupdatemethod',
            index=models.Index(fields=['schedule'], name='dim_update__schedul_5570de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dimupdatemethod',
            unique_together={('name', 'schedule')},
        ),
        migrations.AddIndex(
            model_name='linkupdatecol',
            index=models.Index(fields=['main'], name='link_update_main_id_5bf758_idx'),
        ),
        migrations.AddIndex(
            model_name='linkupdatecol',
            index=models.Index(fields=['sub'], name='link_update_sub_id_ed569d_idx'),
        ),
        migrations.AddIndex(
            model_name='linkupdatecol',
            index=models.Index(fields=['type'], name='link_update_type_id_377096_idx'),
        ),
        migrations.AddConstraint(
            model_name='linkupdatecol',
            constraint=models.UniqueConstraint(fields=('main', 'sub', 'type'), name='unique_update_columns_relation'),
        ),
        migrations.AlterUniqueTogether(
            name='linkupdatecol',
            unique_together={('main', 'sub', 'type')},
        ),
    ]
