# Generated by Django 5.2.7 on 2026-02-02 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dbm', '0001_initial'),
        ('app_updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkupdatecol',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_main', to='app_dbm.linkcolumn', verbose_name='Основная колонка'),
        ),
    ]
