# Generated by Django 5.1.4 on 2026-01-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimupdatemethod',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание расписания.'),
        ),
    ]
