# Generated by Django 5.1.4 on 2026-01-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_updates', '0003_dimupdatemethod_author_dimupdatemethod_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimupdatemethod',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='linkupdatecol',
            name='updated_by',
        ),
    ]
