# Generated by Django 5.1.4 on 2025-08-01 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '01 Категории.',
                'verbose_name_plural': '01 Категории.',
                'db_table': 'my_dictionary"."dim_category',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DimDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_dictionary.dimcategory')),
            ],
            options={
                'verbose_name': '02 Словарь.',
                'verbose_name_plural': '02 Словарь.',
                'db_table': 'my_dictionary"."dim_dictionary',
                'unique_together': {('name', 'category')},
            },
        ),
    ]
