# Generated by Django 5.1.4 on 2025-08-04 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkDictionaryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='запись активна')),
                ('synonym', models.CharField(max_length=255)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='synonyms', to='my_dictionary.dimdictionary')),
            ],
            options={
                'verbose_name': '03 Связь столбцов и синонимом.',
                'verbose_name_plural': '03 Связь столбцов и синонимов.',
                'db_table': 'my_dictionary"."link_dictionary_synonym',
                'unique_together': {('name', 'synonym')},
            },
        ),
    ]
